language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - DOCKER_USERNAME=octoblu
  - DEPLOY_APPLICATION_NAME=little-bits-cloud-proxy
  - DEPLOY_REGION=us-west-2
  - DEPLOY_BUCKET=octoblu-deploy
  - DEPLOYMENT_GROUP=master
  - DEPLOY_KEY=little-bits-cloud-proxy/little-bits-cloud-proxy-$TRAVIS_COMMIT.zip
  - secure: Wg8HBj8tTw5v89g3vPk8g36dcJom7/BdGVJpEg8GmlQy62/U3py36hL5IGzBfLE4XjXwGA3u3uoVB3la1IGvELBi5MSFw5GPDSJfF+uWOSWFt3axglV2hxHF/6dWItX2ssM3HXxNikhmy12pKeGxNxpn5ZoWtSIXgN1l68bcQCybWzFjgugGxpCiPMaMiW35poMs8xbDd2Ve44MiURTi6q/bR8XSKAjXvpBZxBpczyil2qzUbLxi01ySMS73BMp7t2cUAS5BhTDmFKbIwKnGw1jq8llnNCffE424NX6+OhqWpnDp1umAMBDA1XC7TVUpvURwPyD8Yts99srEIaFsGbG4Bq4n1FqrWwwSfeSna/ZW7RRyibYEWLS7kYc/jZs1+YFsoWkx2flmHHRfkGPdpfLS6BCzqGJbGj8g5lo/hlUG7c9POVoLZ5VA8kaXJwLZpCX+npD+Q/AvOahoY9pNTiYGjFYR4lNJXDa8rlBy/luimfaet7eQoUZzNgxDbqBts1R3zsGUGS5Jr3ssyC3zyiR5Cc2bWD5PonQ490tZ/QlQ67xB6Iygd8zJJv733O1PPOEw0dZaRwGrfpTwzxtJOyR3Ycf5TjU1dY5Tj9dzlSrjFNvU2bcEQo/xT+nRM+iIvV43zimD3yDbYXxQWyz9htEqSClvrOVuDOpqd+TVBaI=
  - secure: HrlsCXEj/Fw9+YmBC+RDYjGKwsww4vlNbtqecqmm4oh2b+LZeN9uDmGvuRnVW7YttK9aFh6Inb5gu3U+3J9PMpiKooUMYiDvILKcyp2f6Qn1tXr5WQS8SEuz+Nrj9afAGEsDM/ZmPQYh2ZBQNuLJNll6A1cb/BFVddvSs4WeGhmVgfhSmNDTQJGzRTyN6sdIz/no79ra169tefXjFNX5BZj0dpq3MK1V90rnAg8TMGcOmKtohrtqmvLUyOu9y+jRBZcQqcIjxCZWZRr5H4BZjuN0G/ZzXewyDBoSSHe9KiBehaTe5J9bNhQnq8Fx1ZGoF+5r4kH5XTbwIst1SEMTaKtW1/go7rHgiM9B/ceia7Ytw8Ljj07FEuGLTK2hxYM4AY2WcOmhzMmj86X8d+oqIWkd8j4ApOcIQHb7AWS1NgYYA5/gG5jOggn6vbGQk8cA1nTFn5kr41hemu6fcoJyJW4bgkOzaICJOZTuNku3YJ1YydI2fFq6XgJJZZyYFwvvrR84GKRifFiF+TpnmShU9Tf6IA3AjFGFrVFLLQR5c6F7yEKlIEkfCIBQ7fjmEfUPUQO/dkSTO49HmdT67CPWUGwMBKQT5raydsmpyGWmw3pROcyxFMd93F6r4b1THwka2NJ1xJmvvaYnoFZZVLRqseBm0mZhL++d2MTJCpxIpG4=
after_success:
- .kubernetes/travis_after_success
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: &1
    secure: dIo9vxxD7pu+t6q6d15tJXwQGepFp6XRo/Gd2aVa1KButzSrmMMIaP7Sh8kJEinQeECw/08YRKBUIj7SjrtS/p2Pj6fOdKdZ8tHOlEieeQpdQ3T+7UvDf0u51S50VL3pa3d6GMtGPdC/dvkwX1ck0EuLSjNi9areSYgJGm9VbGzPuMQQO4sGZV5076LxD3X2zAq/pBFqkuxXuSJ7dcgjaH4TFjguS88NlKajAy+zpGSmj/tuYJNTMTp0uGNMm/LBBfBDp4mu8hO8gYL834ajRJdcJgY/gNCTTGi3LdVYJTYUOm00FgPU5EOEr6g+94PhDU6dVIWdAS8zyeDTwwwVACjSooZuceqxJLsa9quhxFrX/K/dxwYxHqQIYKsWA6MZ9PpLLpsctTI8GD9/QVKE1ln+QoPuRPAWJIRfm6p6tShtTmLs2uIt4Km0ACfIQpoBzPR9K2MRJjnTwI/5G5aJTbZg+QOu0NwP8O5ECfUoG8PvxGLUnDEx1+v0rKMT8ILZodUO93JAy0ZyIW32ATaB+T2PTTwrepjWRjm8V9LPVGpkOcd+ZGRcVUcNmrYWTPgn1CKArTMt8ZHhEnLSaEfnqAS34hIKYqZzAqmX1dpT/hjG+4GaUyAzXOTUMSPGjP7T76xmAimIAzw06O2zOLI4khPYmjF+JupbJIwHsfqdaR4=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  bucket: octoblu-deploy
  key: docker-builder/little-bits-cloud-proxy-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: docker-builder
  deployment_group: little-bits-cloud-proxy
  on:
    branch: master
